<a href="https://colab.research.google.com/github/ACORDOBAA/python_fundamentals/blob/branch_6/Ventas_Mensuales_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Importar la librería

import numpy as np

import random

# Creación de arreglo

#matriz_ventas = np.array(["Pelotas de fútbol","Camisetas", "Botines", "Gorras"])

#print(matriz_ventas)

# Modificación de un elemento

#matriz_ventas[2]=3*3

# Otra forma de imprimir la matriz, directamente el nombre de la variable solito
#matriz_2 = np.array([1, True, 9], [4, False, 4], [2, True, 4])
#matriz_2.shape

#ventas_mensuales_random = np.reshape(np.array(randint(10, 51)), (12,4))

#print(ventas_mensuales_random)

ventas_mensuales = np.reshape(np.array(range(1000,1048)), (12,4))

print(ventas_mensuales)

total_ventas_producto = np.sum(ventas_mensuales, axis=0)

print(" ")
#Escribir axis=0 implica que me va a aplicar totales desde arriba hacia abajo (cuatro columnas), si le pongo axis=1 me suma horizontalmente (12 filas, 12 resultados).

print("Los totales de cada producto, para los 12 meses de ventas, son los siguientes")

print(" ")

print(total_ventas_producto)

print(" ")

print("Las ventas totales de cada mes, para los 4 productos, son las siguientes")

print(" ")

total_ventas_mes = np.sum(ventas_mensuales, axis=1)

print(total_ventas_mes)


[[1000 1001 1002 1003]
 [1004 1005 1006 1007]
 [1008 1009 1010 1011]
 [1012 1013 1014 1015]
 [1016 1017 1018 1019]
 [1020 1021 1022 1023]
 [1024 1025 1026 1027]
 [1028 1029 1030 1031]
 [1032 1033 1034 1035]
 [1036 1037 1038 1039]
 [1040 1041 1042 1043]
 [1044 1045 1046 1047]]
 
Los totales de cada producto, para los 12 meses de ventas, son los siguientes
 
[12264 12276 12288 12300]
 
Las ventas totales de cada mes, para los 4 productos, son las siguientes
 
[4006 4022 4038 4054 4070 4086 4102 4118 4134 4150 4166 4182]
